/* Drives the editor through a drag, a marquee and a layer reorder, screenshotting each mid-state. */
import {chromium} from '@playwright/test';
const out=process.argv[2]??'.';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1400,height:900},colorScheme:'light'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:4173/app/',{waitUntil:'networkidle'});
await page.click('#new-project');await page.click('[data-template="voice"]');
await page.waitForSelector('.panel-item');
const knob=page.locator('.panel-item').nth(2);
const box=(await knob.boundingBox());
await page.mouse.move(box.x+box.width/2,box.y+box.height/2);
await page.mouse.down();
await page.mouse.move(box.x+box.width/2+40,box.y+box.height/2+30,{steps:6});
await page.waitForTimeout(80);
await page.screenshot({path:`${out}/c-drag.png`,clip:{x:280,y:60,width:800,height:820}});
await page.mouse.up();
await page.keyboard.press('Escape');
const stage=(await page.locator('#panel-stage').boundingBox());
await page.mouse.move(stage.x-40,stage.y+40);
await page.mouse.down();
await page.mouse.move(stage.x+stage.width*.7,stage.y+stage.height*.5,{steps:6});
await page.waitForTimeout(80);
await page.screenshot({path:`${out}/c-marquee.png`,clip:{x:280,y:60,width:800,height:820}});
await page.mouse.up();
await page.hover('#export');await page.waitForTimeout(600);
await page.screenshot({path:`${out}/c-tip.png`,clip:{x:1100,y:0,width:300,height:120}});
if(errors.length)console.log('ERRORS',errors);
await browser.close();
