import type {ComponentDefinition,PartSource} from './model';

/**
 * Citations for the dimensions this library asserts.
 *
 * A cutout figure is worth no more than its source. Anything without an entry
 * here is a generic estimate and the interface says so. `status:'verified'`
 * additionally requires a manufacturer and part number — see catalog.test.ts,
 * which enforces that contract.
 */
const SOURCE={
  pj398sm:{note:'Thonkiconn PJ398SM / PJ301M-12 — 6 mm panel hole, 4.5 mm thread',url:'https://www.thonk.co.uk/shop/thonkiconn/'},
  alpha9:{note:'Taiwan Alpha RD901F 9 mm potentiometer — M7×0.75 bushing',url:'https://www.mouser.com/datasheet/3/140/1/RD901F.pdf'},
  ec11:{note:'Alps Alpine EC11 encoder — M7×0.75 bushing',url:'https://tech.alpsalpine.com/assets/products/catalog/ec11.en.pdf'},
  ptv09:{note:'Bourns PTV09A-6 9 mm potentiometer — M9×0.75 metal threaded bushing, p.3 drawing and Mounting Hardware inset',url:'https://www.bourns.com/docs/Product-Datasheets/PTV09.pdf'},
  eswitch100:{note:'E-Switch 100 series miniature toggle — Ø6.35 panel hole for the 1/4-40 bushing, p.7 Panel Mounting inset',url:'https://configured-product-images.s3.amazonaws.com/Datasheets/100.pdf'},
  sh16k4:{note:'Song Huei 16K4 16 mm potentiometer — Ø7.5 panel hole for the M7×0.75 bushing, drawing 16K-043 mounting-hole inset',url:'https://www.song-huei.com/proimages/PDF/16K4.pdf'},
  m3fine:{note:'ISO 273 fine series clearance hole for M3',url:'https://www.iso.org/standard/4183.html'},
} satisfies Record<string,PartSource>;

/**
 * A part definition.
 *
 * Every field is named. An earlier version took these positionally, which meant
 * a contributor had to count argument positions to know what `11,5,9.5,14`
 * meant — and it is exactly how six parts came to carry `cutout: 0`, exporting
 * panels with no opening for them at all.
 *
 * Required: what the part is, how big it is, and how much room it needs behind
 * the panel. Everything else is optional and defaults sensibly.
 */
type PartInput=
  Pick<ComponentDefinition,'id'|'name'|'category'|'renderer'|'width'|'height'|'keepout'|'color'|'label'|'description'>
  &Partial<Omit<ComponentDefinition,'id'|'name'|'category'|'renderer'|'width'|'height'|'keepout'|'color'|'label'|'description'>>;

const part=(p:PartInput):ComponentDefinition=>({
  status:'generic',
  tags:[p.name.toLowerCase(),p.category.toLowerCase(),p.renderer],
  ...p,
});

export const catalog:ComponentDefinition[]=[
  part({
    id:'knob-small', name:'Small knob',
    category:'Controls', renderer:'knob',
    width:10, height:10, keepout:12,
    cutout:7,
    color:'#242520', label:'LEVEL',
    description:'Compact 10 mm cap · 7 mm panel cutout',
    depth:14,
    libraryHidden:true,
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-medium', name:'Standard knob',
    category:'Controls', renderer:'knob',
    width:15, height:15, keepout:18,
    cutout:7,
    color:'#242520', label:'FREQUENCY',
    description:'General-purpose potentiometer knob',
    depth:14,
    sizePresets:[{label:'Small · 10 mm',componentId:'knob-small'},{label:'Medium · 15 mm',componentId:'knob-medium'},{label:'Large · 24 mm',componentId:'knob-large'}],
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-large', name:'Large knob',
    category:'Controls', renderer:'knob',
    width:24, height:24, keepout:28,
    cutout:7,
    color:'#242520', label:'TUNING',
    description:'Performance-sized 24 mm cap',
    depth:14,
    libraryHidden:true,
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-skirted', name:'Skirted knob',
    category:'Controls', renderer:'knob',
    width:20, height:20, keepout:23,
    cutout:7,
    color:'#e5e3da', label:'AMOUNT',
    description:'Skirted cap with value scale',
    tags:['knob','skirted','potentiometer'],
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-fluted', name:'Fluted pointer knob',
    category:'Controls', renderer:'knob',
    width:16, height:16, keepout:19,
    cutout:7,
    color:'#252823', label:'AMOUNT',
    description:'Fluted cap with high-contrast pointer',
    depth:14,
    tags:['knob','fluted','pointer','potentiometer'],
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-soft-touch', name:'Soft-touch knob',
    category:'Controls', renderer:'knob',
    width:18, height:18, keepout:21,
    cutout:7,
    color:'#343936', label:'TONE',
    description:'Low-profile rubberized performance cap',
    depth:14,
    tags:['knob','soft touch','rubber','potentiometer'],
    source:SOURCE.alpha9,
  }),
  part({
    id:'encoder', name:'Endless encoder + push',
    category:'Controls', renderer:'knob',
    width:14, height:14, keepout:17,
    cutout:7.2,
    color:'#32342f', label:'SELECT',
    description:'Endless rotary encoder with integral push switch',
    depth:16,
    tags:['encoder','endless','push','click','rotary'],
    source:SOURCE.ec11,
  }),
  part({
    id:'encoder-compact', name:'Compact endless encoder + push',
    category:'Controls', renderer:'knob',
    width:11, height:11, keepout:14,
    cutout:7.2,
    color:'#292c28', label:'VALUE',
    description:'Compact endless encoder with integral push switch',
    depth:15,
    tags:['encoder','endless','push','compact','rotary'],
    source:SOURCE.ec11,
  }),
  part({
    id:'encoder-large', name:'Large endless encoder + push',
    category:'Controls', renderer:'knob',
    width:20, height:20, keepout:24,
    cutout:7.2,
    color:'#2b2e2a', label:'BROWSE',
    description:'Performance-sized endless encoder with push switch',
    depth:17,
    tags:['encoder','endless','push','large','rotary'],
    source:SOURCE.ec11,
  }),
  part({
    id:'encoder-ring', name:'Illuminated encoder + push',
    category:'Controls', renderer:'knob',
    width:22, height:22, keepout:26,
    cutout:8,
    color:'#202421', label:'SELECT',
    description:'Endless push encoder with illuminated halo',
    depth:18,
    tags:['encoder','endless','push','illuminated','led ring','rotary'],
    source:SOURCE.ec11,
  }),
  part({
    id:'encoder-metal', name:'Metal encoder + push',
    category:'Controls', renderer:'knob',
    width:16, height:16, keepout:20,
    cutout:7.2,
    color:'#aeb3ac', label:'DATA',
    description:'Machined aluminium endless push encoder',
    depth:17,
    tags:['encoder','endless','push','metal','rotary'],
    source:SOURCE.ec11,
  }),
  part({
    id:'knob-concentric', name:'Concentric knob',
    category:'Controls', renderer:'knob',
    width:18, height:18, keepout:22,
    cutout:8,
    color:'#252622', label:'COARSE / FINE',
    description:'Dual concentric control',
    depth:18,
    source:SOURCE.alpha9,
  }),
  part({
    id:'knob-16mm', name:'Knob on 16 mm pot',
    category:'Controls', renderer:'knob',
    width:20, height:20, keepout:23,
    cutout:7.5,
    color:'#242520', label:'CUTOFF',
    description:'Song Huei 16K4 16 mm pot · Ø7.5 panel hole. The pot also wants a Ø3 anti-rotation hole 7.8 mm off-centre, which Five08 does not cut',
    depth:9.3,
    tags:['knob','16 mm','potentiometer','song huei','16k4'],
    source:SOURCE.sh16k4,
  }),
  part({
    id:'knob-ptv09', name:'Knob on Bourns PTV09',
    category:'Controls', renderer:'knob',
    width:15, height:15, keepout:18,
    cutout:9.1,
    color:'#242520', label:'LEVEL',
    description:'Bourns PTV09A-6 9 mm pot, M9×0.75 threaded bushing · 9.1 mm panel hole. The other PTV09 bushings are plain or absent and need a different hole',
    depth:10.4,
    tags:['knob','potentiometer','bourns','ptv09','9 mm'],
    source:SOURCE.ptv09,
  }),
  part({
    id:'slider-20', name:'Vertical slider',
    category:'Controls', renderer:'slider',
    width:10, height:28, keepout:14,
    cutout:2.2,
    color:'#d8d8d0', label:'LEVEL',
    description:'Vertical panel fader',
    cutoutShape:'obround',
    cutoutInset:.85,
    cutoutWidth:2.2,
    orientation:'vertical',
    depth:12,
    sizePresets:[{label:'20 mm travel',componentId:'slider-20'},{label:'30 mm travel',componentId:'slider-30'},{label:'45 mm travel',componentId:'slider-45'}],
  }),
  part({
    id:'slider-30', name:'30 mm slider',
    category:'Controls', renderer:'slider',
    width:10, height:38, keepout:14,
    cutout:2.2,
    color:'#d8d8d0', label:'LEVEL',
    description:'30 mm travel vertical fader',
    cutoutShape:'obround',
    cutoutInset:.85,
    cutoutWidth:2.2,
    orientation:'vertical',
    depth:12,
    libraryHidden:true,
  }),
  part({
    id:'slider-45', name:'45 mm slider',
    category:'Controls', renderer:'slider',
    width:10, height:53, keepout:14,
    cutout:2.2,
    color:'#d8d8d0', label:'LEVEL',
    description:'45 mm travel vertical fader',
    cutoutShape:'obround',
    cutoutInset:.85,
    cutoutWidth:2.2,
    orientation:'vertical',
    depth:14,
    libraryHidden:true,
  }),
  part({
    id:'crossfader', name:'Horizontal crossfader',
    category:'Controls', renderer:'slider',
    width:43, height:10, keepout:14,
    cutout:2.2,
    color:'#d8d8d0', label:'MIX',
    description:'Horizontal performance fader',
    cutoutShape:'obround',
    cutoutInset:.85,
    cutoutHeight:2.2,
    orientation:'horizontal',
    depth:12,
  }),
  part({
    id:'joystick', name:'Joystick',
    category:'Controls', renderer:'touch',
    width:25, height:25, keepout:31,
    cutout:12,
    color:'#262824', label:'X / Y',
    description:'Two-axis joystick',
    depth:28,
  }),
  part({
    id:'touch-strip', name:'Touch strip',
    category:'Controls', renderer:'touch',
    width:12, height:48, keepout:15,
    color:'#b8ff65', label:'TOUCH',
    description:'Capacitive touch strip, mounted on the panel face with no opening',
    depth:3,
  }),

  part({
    id:'jack-mono', name:'3.5 mm mono jack',
    category:'Jacks & connectors', renderer:'jack',
    width:9, height:9, keepout:12,
    cutout:6.2,
    color:'#171815', label:'IN',
    description:'Generic vertical mono jack',
    depth:12,
  }),
  part({
    id:'jack-stereo', name:'3.5 mm TRS jack',
    category:'Jacks & connectors', renderer:'jack',
    width:9, height:9, keepout:12,
    cutout:6.2,
    color:'#171815', label:'STEREO',
    description:'Stereo/switching jack',
    depth:12,
  }),
  part({
    id:'jack-thonk', name:'Thonkiconn jack',
    category:'Jacks & connectors', renderer:'jack',
    width:10, height:10, keepout:12,
    cutout:6,
    color:'#171815', label:'CV',
    description:'PJ398SM-style vertical jack',
    manufacturer:'Wenzhou QingPu',
    partNumber:'PJ398SM',
    status:'verified',
    depth:11,
    source:SOURCE.pj398sm,
  }),
  part({
    id:'banana', name:'Banana socket',
    category:'Jacks & connectors', renderer:'jack',
    width:12, height:12, keepout:15,
    cutout:8,
    color:'#e84f3c', label:'PATCH',
    description:'4 mm banana socket',
    depth:20,
  }),
  part({
    id:'usb-c', name:'USB-C receptacle',
    category:'Jacks & connectors', renderer:'connector',
    width:11, height:5, keepout:14,
    cutout:9.5,
    color:'#9da29c', label:'USB',
    description:'Panel USB-C opening',
    depth:10,
    cutoutShape:'rect',
    cutoutWidth:9.5,
    cutoutHeight:3.5,
  }),
  part({
    id:'midi-trs', name:'MIDI TRS',
    category:'Jacks & connectors', renderer:'jack',
    width:10, height:10, keepout:13,
    cutout:6.5,
    color:'#171815', label:'MIDI',
    description:'3.5 mm MIDI TRS jack',
    depth:12,
  }),
  part({
    id:'midi-din', name:'MIDI DIN',
    category:'Jacks & connectors', renderer:'connector',
    width:20, height:20, keepout:24,
    cutout:15,
    color:'#151614', label:'MIDI',
    description:'5-pin DIN socket',
    depth:22,
  }),
  part({
    id:'sd-slot', name:'Micro SD slot',
    category:'Jacks & connectors', renderer:'connector',
    width:14, height:4, keepout:18,
    cutout:12,
    color:'#11120f', label:'SD',
    description:'Micro SD card opening',
    depth:12,
    cutoutShape:'rect',
    cutoutWidth:12,
    cutoutHeight:2.6,
  }),

  part({
    id:'button-tact', name:'Tactile button',
    category:'Switches & buttons', renderer:'button',
    width:7, height:7, keepout:10,
    cutout:3.5,
    color:'#e8e7df', label:'STEP',
    description:'6 × 6 mm tactile switch',
    depth:8,
  }),
  part({
    id:'button-round', name:'Round pushbutton',
    category:'Switches & buttons', renderer:'button',
    width:10, height:10, keepout:14,
    cutout:7,
    color:'#e8e7df', label:'TRIGGER',
    description:'Momentary round pushbutton',
    depth:15,
  }),
  part({
    id:'button-square', name:'Square pushbutton',
    category:'Switches & buttons', renderer:'button',
    width:12, height:12, keepout:15,
    cutout:9,
    color:'#ecebe4', label:'MODE',
    description:'Square cap pushbutton',
    depth:14,
    cutoutShape:'rect',
    cutoutWidth:9,
    cutoutHeight:9,
  }),
  part({
    id:'button-lit', name:'Illuminated button',
    category:'Switches & buttons', renderer:'button',
    width:12, height:12, keepout:15,
    cutout:8,
    color:'#ff7254', label:'RECORD',
    description:'Illuminated momentary button',
    depth:18,
  }),
  part({
    id:'button-lit-square', name:'Illuminated square button',
    category:'Switches & buttons', renderer:'button',
    width:12, height:12, keepout:16,
    cutout:9,
    color:'#ff6d55', label:'STEP',
    description:'12 mm square illuminated momentary button',
    depth:18,
    cutoutShape:'rect',
    cutoutWidth:9,
    cutoutHeight:9,
    tags:['button','square','illuminated','led','momentary'],
  }),
  part({
    id:'button-lit-square-large', name:'Large illuminated square',
    category:'Switches & buttons', renderer:'button',
    width:16, height:16, keepout:20,
    cutout:12,
    color:'#8fe46d', label:'LAUNCH',
    description:'16 mm square illuminated performance button',
    depth:21,
    cutoutShape:'rect',
    cutoutWidth:12,
    cutoutHeight:12,
    tags:['button','square','illuminated','led','large','momentary'],
  }),
  part({
    id:'button-lit-rect', name:'Illuminated rectangular button',
    category:'Switches & buttons', renderer:'button',
    width:18, height:10, keepout:22,
    cutout:8,
    color:'#70cfff', label:'SHIFT',
    description:'Compact rectangular illuminated momentary button',
    depth:18,
    orientation:'horizontal',
    cutoutShape:'rect',
    cutoutWidth:14.4,
    cutoutHeight:8,
    tags:['button','rectangular','illuminated','led','momentary'],
  }),
  part({
    id:'button-lit-wide', name:'Wide illuminated button',
    category:'Switches & buttons', renderer:'button',
    width:24, height:11, keepout:28,
    cutout:9,
    color:'#ffd25f', label:'PLAY / STOP',
    description:'Wide rectangular illuminated transport button',
    depth:20,
    orientation:'horizontal',
    cutoutShape:'rect',
    cutoutWidth:19.2,
    cutoutHeight:8.8,
    tags:['button','rectangular','wide','illuminated','transport','led'],
  }),
  part({
    id:'button-arcade', name:'Arcade button',
    category:'Switches & buttons', renderer:'button',
    width:24, height:24, keepout:29,
    cutout:20,
    color:'#e55278', label:'TRIGGER',
    description:'Large performance arcade-style momentary button',
    depth:32,
    tags:['button','arcade','large','performance','momentary'],
  }),
  part({
    id:'button-metal', name:'Metal pushbutton',
    category:'Switches & buttons', renderer:'button',
    width:16, height:16, keepout:20,
    cutout:12,
    color:'#b8bdb7', label:'POWER',
    description:'Metal anti-vandal momentary pushbutton',
    depth:24,
    tags:['button','metal','anti vandal','momentary'],
  }),
  part({
    id:'toggle-2', name:'2-position toggle',
    category:'Switches & buttons', renderer:'toggle',
    width:10, height:14, keepout:14,
    cutout:6.35,
    color:'#d8d8d0', label:'ON',
    description:'Miniature two-position toggle, 1/4-40 bushing (E-Switch 100 series) · Ø6.35 panel hole. The anti-rotation keyway is not modelled — cut it separately or use the locking washer',
    depth:18,
    source:SOURCE.eswitch100,
  }),
  part({
    id:'toggle-3', name:'3-position toggle',
    category:'Switches & buttons', renderer:'toggle',
    width:10, height:14, keepout:14,
    cutout:6.35,
    color:'#d8d8d0', label:'MODE',
    description:'Miniature three-position toggle, 1/4-40 bushing (E-Switch 100 series) · Ø6.35 panel hole. The anti-rotation keyway is not modelled — cut it separately or use the locking washer',
    depth:18,
    source:SOURCE.eswitch100,
  }),
  part({
    id:'slide-switch', name:'Slide switch',
    category:'Switches & buttons', renderer:'toggle',
    width:12, height:7, keepout:15,
    cutout:8,
    color:'#d8d8d0', label:'RANGE',
    description:'Compact slide switch',
    cutoutShape:'obround',
    cutoutWidth:8,
    cutoutHeight:3,
    orientation:'horizontal',
    depth:8,
  }),
  part({
    id:'rotary-switch', name:'Rotary selector',
    category:'Switches & buttons', renderer:'knob',
    width:18, height:18, keepout:22,
    cutout:10,
    color:'#e2e0d7', label:'RANGE',
    description:'Multi-position rotary selector',
    depth:22,
  }),

  part({
    id:'led-2mm', name:'2 mm LED',
    category:'Indicators & displays', renderer:'led',
    width:2, height:2, keepout:4,
    cutout:2.1,
    color:'#ff6045', label:'',
    description:'Discrete 2 mm indicator',
    libraryHidden:true,
  }),
  part({
    id:'led-3mm', name:'Panel LED',
    category:'Indicators & displays', renderer:'led',
    width:3, height:3, keepout:5,
    cutout:3.1,
    color:'#ff6045', label:'',
    description:'Discrete panel indicator',
    sizePresets:[{label:'2 mm',componentId:'led-2mm'},{label:'3 mm',componentId:'led-3mm'},{label:'5 mm',componentId:'led-5mm'}],
  }),
  part({
    id:'led-5mm', name:'5 mm LED',
    category:'Indicators & displays', renderer:'led',
    width:5, height:5, keepout:7,
    cutout:5.1,
    color:'#b7ff54', label:'',
    description:'Discrete 5 mm indicator',
    libraryHidden:true,
  }),
  part({
    id:'led-rgb', name:'RGB LED',
    category:'Indicators & displays', renderer:'led',
    width:5, height:5, keepout:7,
    cutout:5.1,
    color:'#70d7ff', label:'RGB',
    description:'Full-colour indicator',
  }),
  part({
    id:'led-ring', name:'LED ring',
    category:'Indicators & displays', renderer:'led',
    width:22, height:22, keepout:25,
    color:'#b7ff54', label:'VALUE',
    description:'12 discrete LEDs — drill each one separately, Five08 cannot express the ring as a single cutout',
  }),
  part({
    id:'bargraph', name:'10-segment bargraph',
    category:'Indicators & displays', renderer:'display',
    width:7, height:26, keepout:10,
    cutout:6,
    color:'#b7ff54', label:'LEVEL',
    description:'Vertical 10-segment LED meter',
    cutoutShape:'rect',
  }),
  part({
    id:'seven-seg', name:'7-segment display',
    category:'Indicators & displays', renderer:'display',
    width:14, height:9, keepout:18,
    cutout:11,
    color:'#ff765c', label:'VALUE',
    description:'Two-digit numeric display',
    cutoutShape:'rect',
  }),
  part({
    id:'oled-091', name:'0.91 in OLED',
    category:'Indicators & displays', renderer:'display',
    width:25, height:10, keepout:29,
    cutout:22,
    color:'#8effc6', label:'STATUS',
    description:'128 × 32 OLED viewport',
    cutoutShape:'rect',
    cutoutInset:.86,
    depth:5,
  }),
  part({
    id:'oled-096', name:'0.96 in OLED',
    category:'Indicators & displays', renderer:'display',
    width:25, height:15, keepout:29,
    cutout:22,
    color:'#8effc6', label:'STATUS',
    description:'128 × 64 OLED viewport',
    cutoutShape:'rect',
    cutoutInset:.86,
    depth:5,
  }),
  part({
    id:'oled-13', name:'1.3 in OLED',
    category:'Indicators & displays', renderer:'display',
    width:35, height:18, keepout:40,
    cutout:31,
    color:'#8effc6', label:'DISPLAY',
    description:'Large OLED viewport',
    cutoutShape:'rect',
    cutoutInset:.86,
    depth:6,
  }),
  part({
    id:'vu-meter', name:'Analogue VU meter',
    category:'Indicators & displays', renderer:'display',
    width:32, height:24, keepout:38,
    cutout:28,
    color:'#f3dca4', label:'LEVEL',
    description:'Backlit moving-coil meter',
    cutoutShape:'rect',
    cutoutInset:.86,
    depth:25,
  }),

  part({
    id:'mount-hole', name:'M3 mounting hole',
    category:'Panel hardware', renderer:'hole',
    width:3.2, height:3.2, keepout:5,
    cutout:3.2,
    color:'#999b94', label:'',
    description:'M3 clearance hole',
    status:'verified',
    source:SOURCE.m3fine,
    manufacturer:'ISO 273',
    partNumber:'M3 fine',
  }),
  part({
    id:'mount-slot', name:'M3 mounting slot',
    category:'Panel hardware', renderer:'hole',
    width:6.5, height:3.2, keepout:8,
    cutout:3.2,
    color:'#999b94', label:'',
    description:'Horizontal M3 mounting slot',
    status:'verified',
    orientation:'horizontal',
    source:SOURCE.m3fine,
    manufacturer:'ISO 273',
    partNumber:'M3 fine',
  }),
  part({
    id:'vent-slot', name:'Ventilation slot',
    category:'Panel hardware', renderer:'hole',
    width:14, height:2.5, keepout:4,
    cutout:2.5,
    color:'#34352f', label:'',
    description:'Rounded ventilation slot, cut at the size you draw it',
    orientation:'horizontal',
  }),
  part({
    id:'cutout-circle', name:'Circular cutout',
    category:'Panel hardware', renderer:'shape',
    width:12, height:12, keepout:14,
    cutout:12,
    color:'#30312d', label:'',
    description:'Parametric circular opening',
  }),
  part({
    id:'cutout-rect', name:'Rectangular cutout',
    category:'Panel hardware', renderer:'shape',
    width:18, height:10, keepout:21,
    cutout:18,
    color:'#30312d', label:'',
    description:'Rectangular opening, cut at the size you draw it',
    cutoutShape:'rect',
    cutoutInset:1,
  }),
  part({
    id:'standoff', name:'PCB standoff',
    category:'Panel hardware', renderer:'hole',
    width:3, height:3, keepout:6,
    cutout:3,
    color:'#8e9188', label:'',
    description:'PCB mounting reference',
    depth:8,
  }),

  part({
    id:'text-label', name:'Text label',
    category:'Graphics', renderer:'text',
    width:20, height:4, keepout:0,
    color:'#f2f2eb', label:'LABEL',
    description:'Panel legend — multi-line, with a choice of font, weight and alignment',
    tags:['text','label','legend','type','font'],
  }),
  part({
    id:'knob-scale', name:'Knob scale',
    category:'Graphics', renderer:'scale',
    width:26, height:26, keepout:0,
    color:'#f2f2eb', label:'',
    description:'270° tick arc to print around a knob',
    resizable:true,
    tags:['scale','ticks','dial','marks','knob'],
  }),
  part({
    id:'arrow', name:'Signal arrow',
    category:'Graphics', renderer:'arrow',
    width:14, height:2.6, keepout:0,
    color:'#f2f2eb', label:'',
    description:'Flow arrow — rotate it to aim',
    resizable:true,
    tags:['arrow','signal','flow','routing'],
  }),
  part({
    id:'section-title', name:'Section title',
    category:'Graphics', renderer:'text',
    width:28, height:6, keepout:0,
    color:'#f2f2eb', label:'SECTION',
    description:'Large section heading',
  }),
  part({
    id:'divider', name:'Divider line',
    category:'Graphics', renderer:'shape',
    width:28, height:1, keepout:0,
    color:'#ff5d3b', label:'',
    description:'Graphic section divider',
  }),
  part({
    id:'shape-circle', name:'Circle',
    category:'Graphics', renderer:'shape',
    width:12, height:12, keepout:0,
    color:'#ff5d3b', label:'',
    description:'Graphic circle or ring',
  }),
  part({
    id:'shape-rect', name:'Rectangle',
    category:'Graphics', renderer:'shape',
    width:20, height:10, keepout:0,
    color:'#ff5d3b', label:'',
    description:'Graphic rectangle',
  }),
  part({
    id:'png-image', name:'PNG image',
    category:'Graphics', renderer:'image',
    width:30, height:30, keepout:0,
    color:'#ff5d3b', label:'',
    description:'Transparent, resizable panel artwork',
    tags:['png','image','artwork','graphic','texture','logo','transparent'],
  }),
];

export const catalogMap=new Map(catalog.map(d=>[d.id,d]));
export const categories=[...new Set(catalog.map(d=>d.category))];
