import './landing.css';

const mark=`<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M18 11h28M18 53h28"/><rect x="21" y="8" width="22" height="48" rx="4"/><circle class="signal" cx="32" cy="32" r="7"/><circle cx="32" cy="32" r="2.5"/></svg>`;
const arrow=`<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h12m-5-5 5 5-5 5"/></svg>`;

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<div class="site-shell">
 <header class="site-nav"><a class="site-logo" href="/">${mark}<span>five08</span></a><nav aria-label="Main navigation"><a href="#features">Features</a><a href="#workflow">Workflow</a><a href="#about">About</a><a href="https://github.com/alibros/five08" target="_blank" rel="noreferrer">GitHub</a></nav><a class="nav-cta" href="/app/">Open designer ${arrow}</a></header>
 <main>
  <section class="hero"><div class="hero-copy"><p class="kicker"><span></span> Eurorack panel design</p><h1>Lay out a Eurorack panel<br>before drilling anything.</h1><p class="hero-lede">Five08 is a free, open-source panel layout tool. Set the HP, place parts in millimetres, check spacing, and export the result.</p><div class="hero-actions"><a class="primary-cta" href="/app/">Open the designer ${arrow}</a><a class="text-link" href="#features">What is included <span>↓</span></a></div><p class="trust"><span>●</span> Free and open source&nbsp;&nbsp;·&nbsp;&nbsp;No account&nbsp;&nbsp;·&nbsp;&nbsp;Files stay on your computer</p></div><div class="hero-object" aria-label="A designed Eurorack panel"><div class="measurement top">12 HP / 60.56 MM</div><div class="measurement side">128.5 MM</div><div class="hero-panel"><div class="rail top-rail"></div><div class="rail bottom-rail"></div><div class="panel-title">FIVE08<br><small>FIELD STUDY</small></div><div class="control hero-knob k1"><i></i><label>FREQUENCY</label></div><div class="control hero-knob k2"><i></i><label>SHAPE</label></div><div class="control hero-knob k3"><i></i><label>SPACE</label></div><div class="control hero-jack j1"><i></i><label>V/OCT</label></div><div class="control hero-jack j2"><i></i><label>MOD</label></div><div class="control hero-jack j3"><i></i><label>OUT</label></div><div class="smart-line-demo"><b>15.0 mm</b></div></div><span class="object-note">12 HP panel, shown at<br>real dimensions.</span></div></section>
  <section class="name-strip"><div><span class="big-number">5.08</span><p><strong>1 HP is 5.08 mm.</strong> That is the reference for panel width, component positions, spacing, rulers, and exports.</p></div></section>
  <section class="features" id="features"><div class="section-heading"><p class="kicker"><span></span> The basics</p><h2>Panel layout,<br>in millimetres.</h2><p>Useful for sketching a module faceplate before committing to hardware or artwork.</p></div><div class="feature-grid"><article><span class="feature-no">01</span><div class="feature-visual visual-scale"><div class="mini-panel"></div><i>128.5</i><b>12 HP</b></div><h3>Lay out at real scale</h3><p>Accurate HP sizing, millimetre coordinates, rulers, panel-safe areas, and manufactured-width profiles.</p></article><article><span class="feature-no">02</span><div class="feature-visual visual-guides"><i></i><i></i><i></i><span>12.0</span><span>12.0</span></div><h3>Line things up</h3><p>Snap to centres and edges, compare gaps, or distribute a group evenly.</p></article><article><span class="feature-no">03</span><div class="feature-visual visual-parts"><i class="pv-knob"></i><i class="pv-button"></i><i class="pv-jack"></i><i class="pv-screen"></i></div><h3>Use common panel parts</h3><p>Knobs, encoders, illuminated buttons, jacks, screens, sliders, PNG artwork, and mechanical references.</p></article></div></section>
  <section class="product" id="workflow"><div class="product-copy"><p class="kicker light"><span></span> Views</p><h2>Three useful<br>views.</h2><p>Use the normal panel view for layout, then inspect cutouts or rear clearances when needed.</p><ul><li><b>Hardware</b><span>Controls, labels, and artwork</span></li><li><b>Cutouts</b><span>Drilling and aperture geometry</span></li><li><b>Rear</b><span>Component bodies and keepouts</span></li></ul></div><div class="editor-preview"><div class="preview-top"><span class="preview-logo">five08</span><span>Ambient voice</span><b>Export</b></div><div class="preview-body"><div class="preview-library"><small>COMPONENTS</small><div></div><div></div><div></div><div></div></div><div class="preview-canvas"><div class="preview-panel"><i></i><i></i><i></i><i></i><i></i><i></i><span class="guide-a"></span><span class="guide-label">14.0 mm</span></div></div><div class="preview-inspector"><small>INSPECT</small><span></span><span></span><span></span><span></span></div></div></div></section>
  <section class="materials"><div class="section-heading"><p class="kicker"><span></span> Panel presets</p><h2>Pick a panel<br>finish.</h2></div><div class="material-row"><div class="material silver"><span>Brushed<br>aluminium</span></div><div class="material black"><span>Black<br>anodized</span></div><div class="material acrylic"><span>Smoke<br>acrylic</span></div><div class="material fr4"><span>Green<br>FR4</span></div><div class="material walnut"><span>Bead-blasted<br>aluminium</span></div></div></section>
  <section class="exports"><div><p class="kicker"><span></span> Files</p><h2>Export the<br>files.</h2><p>Download the editable project, physical-size SVGs, a parts list, or VCV Rack helper artwork.</p></div><div class="export-list"><span><b>SVG</b> Panel artwork</span><span><b>SVG</b> Cutout geometry</span><span><b>CSV</b> Bill of materials</span><span><b>JSON</b> Editable project</span><span><b>VCV</b> Rack helper panel</span></div></section>
  <section class="final-cta"><p class="kicker light"><span></span> Open source</p><h2>Free to use.<br>Runs locally.</h2><a class="primary-cta light-button" href="/app/">Open Five08 ${arrow}</a></section>
 </main>
 <footer id="about"><a class="site-logo footer-logo" href="/">${mark}<span>five08</span></a><p>Designed and built by <a href="https://forestofrods.com" target="_blank" rel="noreferrer">Ali Bross</a> for instrument makers, module designers, and curious builders.</p><div><a href="https://forestofrods.com" target="_blank" rel="noreferrer">Forest of Rods</a><a href="https://github.com/alibros/five08" target="_blank" rel="noreferrer">GitHub</a><a href="mailto:ali@forestofrods.com">Contact</a></div><small>Verify component dimensions against manufacturer datasheets before fabrication. © 2026 Ali Bross.</small></footer>
</div>`;
